### ISSUE TITLE
FDC3 Workbench not loading and has an error

### ISSUE THREAD

**Issue by gerard-ciq** [finos/FDC3#1567]
## Minor Issue
Please use minor issues for discrepancies or errors found in the spec or supporting documentation, examples, and other materials.  If you wish to propose a new feature or a revision to an existing feature, please use the *Enhancement Request* template.

### Area of Issue
 - [ ] App Directory
 - [ ] API
 - [ ] Context Data
 - [ ] Intents
 - [ ] Desktop Agent Bridging
 - [ ] Use Cases
 - [x] Other

### Issue Description: 
When I load https://fdc3.finos.org/toolbox/fdc3-workbench in a desktop agent or browser, the screen is blank. The console contains the following errors in the browser:

![Image](https://github.com/user-attachments/assets/6e733f4d-f3d7-4eb0-8915-78b627765e3e)

And these errors in the Desktop Agent:

![Image](https://github.com/user-attachments/assets/7d5501fb-f0a2-4fbd-9857-bb717179ddba)

### Additional Context:
Everything works when I build it locally. The issue only occurs with the official hosted version.

**Comment by robmoffat** [comment]
Fixed by #1566

**Comment by robmoffat** [comment]
Thanks for reporting though!

**Comment by robmoffat** [comment]
Fixed now @gerard-ciq - Can you confirm?

**Comment by kruplm** [comment]
Hi @robmoffat! One of the issues is still there:

![Image](https://github.com/user-attachments/assets/09826ae7-5b69-4170-9718-fc5c09595e43)

The workbench fails to retrive the user channels.

Should I create a new issue or will you reopen this one?
